spring:
  application:
    name: marathon

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/marathon?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

server:
  port: 8123