spring:
  application:
    name: marathon

  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@marathon-documnetdb.cvicueceetyt.ap-northeast-2.docdb.amazonaws.com:27017/${MONGODB_DATABASE}?tls=true&tlsCAFile=global-bundle.pem&retryWrites=false

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

server:
  port: 8080